library(lubridate)
data <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
data$Date <- dmy(data$Date)
data <- subset(data, data$Date == as.Date("2007-02-01") | data$Date == as.Date("2007-02-02"))
dateandtime <- ymd_hms(paste(data$Date, data$Time))
png("plot2.png", width = 480, height = 480)
plot(dateandtime, data$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()
